### ISSUE TITLE
Installation fails with `FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!`

### ISSUE THREAD

**Issue by dpole** [JulienPeloton/s4cmb#11]
I encountered this error while installing `s4cmb` on MacOS High Sierra.
Doing
```
export PATH=/usr/bin:$PATH
```
before installing worked for me.

It was an issue with my environment rather then the repo. I report it here in case someone else has the same problem.

**Comment by JulienPeloton** [comment]
Thanks! I did not upgrade to High Sierra yet, so you saved me a lot of time with this solution ;-)
Actually I may consider adding osx in Travis (only Ubuntu/Trusty is checked so far).

**Comment by xavierbourretsicotte** [comment]
Thanks a bunch - solved a similar problem on LightGBM for me. Where I had exactly the same error message.

https://github.com/Microsoft/LightGBM/issues/1369
