### ISSUE TITLE
loading s4cmb modules from NERSC jupyter 

### ISSUE THREAD

**Issue by MariaJK** [JulienPeloton/s4cmb#16]
Hi Julien,

I am sorry, I cannot load s4cmb from NERSC jupyter.
Here is the sequence of commands I did:

(from a putty terminal)
I did:

$ module unload intel
$ module load gcc/4.9.3 

$ module load python/2.7-anaconda
$ pip install s4cmb --user
$ pip install -r requirements.txt
$ make

(I didn't find errors in running up to 'make' command).

and then I open the jupyter notebook from 

https://jupyter-dev.nersc.gov

The notebook does not find the module 'instrument' and the following ones (see attached snapshots of my account).

I have tried also loading
$ module load python/2.7-anaconda-4.4
without any difference.

Thanks,
Maria

![nersc4](https://user-images.githubusercontent.com/20668298/33296880-53d4a098-d3b4-11e7-9d00-da0caa51fa17.jpg)
![nersc5](https://user-images.githubusercontent.com/20668298/33296881-53f1e7de-d3b4-11e7-875c-ad892bd1c1e1.jpg)
![nersc6](https://user-images.githubusercontent.com/20668298/33296882-54089a06-d3b4-11e7-8e21-a62025afe0ce.jpg)

**Comment by JulienPeloton** [comment]
Hi Maria,

I think you do not have your paths to your pip packages loaded by default loaded in jupyter.
If you did a pip installation of the packages, try doing this at the beginning of your notebook:

```python
path_to_pip = "/global/homes/s/salatino/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages"
os.sys.path.insert(0, os.path.realpath(path_to_pip))
```

**Comment by MariaJK** [comment]
Hi Julien,

I did this:

$ from __future__ import division, absolute_import, print_function
$ import os
$ path_to_pip = "/global/homes/s/salatino/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages"
$ os.sys.path.insert(0, os.path.realpath(path_to_pip))
$ path_to_s4cmb = '/global/u1/s/salatino/cori/s4cmb/'
$ os.sys.path.insert(0, os.path.realpath(path_to_s4cmb))

now I can load, for example, the ephem module but still it does found s4cmb:

$ from s4cmb import instrument

ImportErrorTraceback (most recent call last)
<ipython-input-85-2513657833cd> in <module>()
----> 1 from s4cmb import instrument

/global/u1/s/salatino/cori/s4cmb/s4cmb/__init__.py in <module>()
----> 1 from s4cmb import instrument
      2 from s4cmb import scanning_strategy
      3 from s4cmb import input_sky
      4 from s4cmb import detector_pointing
      5 from s4cmb import tod

ImportError: cannot import name instrument

-------------------------------------------------------------------------------
also it does not find healpy:

$ import healpy

ImportErrorTraceback (most recent call last)
<ipython-input-98-c6580042a8d8> in <module>()
----> import healpy

/global/u1/s/salatino/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages/healpy/__init__.py in <module>()
       get_map_size)
    
---> +from .sphtfunc import (anafast, map2alm,
 alm2map, Alm, synalm, synfast,
 smoothing, smoothalm, almxfl, alm2cl,

/global/u1/s/salatino/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages/healpy/sphtfunc.py in <module>()
  pi = np.pi
 import warnings
--->  import astropy.io.fits as pf
 from . import _healpy_sph_transform_lib as sphtlib

/usr/common/software/python/2.7-anaconda-4.4/lib/python2.7/site-packages/astropy/io/fits/__init__.py in <module>() 
--->  from . import py3compat
 from ... import config as _config
ImportError: cannot import name py3compat

(but maybe it is not finding other modules before).


Also: did shouldn't be affected by the fact that I haven't update my .bashrc.ext with PYTHONPATH variable... (right?)

Thanks for your attention,
Maria

**Comment by JulienPeloton** [comment]
OK, something you can try first is to add

```bash
export JUPYTER_PATH=$JUPYTER_PATH:$PYTHONPATH
```

in your .bashrc.ext and then reconnect to jupyter. Does that solve some of the problems above?

**Comment by MariaJK** [comment]
Hi Julien,

sorry sorry,
still the same problem
(see attached .bashrc.ext file)
thanks,
Maria
![bashrc](https://user-images.githubusercontent.com/20668298/33323633-64407184-d44d-11e7-8879-febd95b42038.jpg)

**Comment by JulienPeloton** [comment]
wait, did you say you installed s4cmb with pip or you cloned it at NERSC?

**Comment by MariaJK** [comment]
I did:
$ git clone 'url git repository'

**Comment by JulienPeloton** [comment]
Unfortunately, I do not see where is the problem exactly :-(
Probably at that stage you should open a ticket at NERSC, and explain the problem.
Sorry for not being more useful!

**Comment by MariaJK** [comment]
ok, thanks Julien,
I will do it and let you know.
Maria

**Comment by MariaJK** [comment]
Hi Julien,

it seems it works now!
Here is the full list of commands I did:


From a Putty terminal:
I have cloned a git repository 's4cmb'

$ git clone < url of the git hub repository>

(The cloned repository is located on:
/global/u1/s/salatino/cori/s4cmb/ )

$ module unload intel
$ module load gcc/4.9.3

(I have loaded other Fortran compilers since the ones required are not compatible
with the Intel default one).

$ module load python/2.7-anaconda-4.4
$ pip install s4cmb --user
$ cd /global/homes/s/salatino/cori/s4cmb
$ pip install -r requirements.txt
$ make 

(these commands run without any errors)

I have updated my .bashrc.ext file
and add these lines:

$ s4cmbPATH=/global/u1/s/salatino/cori/s4cmb
$ export PYTHONPATH=$PYTHONPATH:$s4cmbPATH
$ export JUPYTER_PATH=$JUPYTER_PATH:$PYTHONPATH

(I checked that these variables are updated:
$ echo $PYTHONPATH

:/global/u1/s/salatino/cori/s4cmb

$ echo $s4cmbPATH

/global/u1/s/salatino/cori/s4cmb
)


I opened a Jupyter notebook from: 
https://jupyter-dev.nersc.gov

and I wrote these commands:

$ from __future__ import division, absolute_import, print_function
$ import os
$ path_to_pip = "/global/homes/s/salatino/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages"
$ os.sys.path.insert(0, os.path.realpath(path_to_pip))
$ path_to_s4cmb = '/global/homes/s/salatino/cori/s4cmb/'
$ os.sys.path.insert(0, os.path.realpath(path_to_s4cmb))

Thanks a lot for your help!
Maria

**Comment by JulienPeloton** [comment]
I'm glad it works!
Out of curiosity, what would be the results of printing in a jupyter notebook cell:

```python
import s4cmb
print(s4cmb.__file__)
```

Does it point to the pip package or the git clone?

**Comment by MariaJK** [comment]
Hi Julien,

it prints:
$ /global/u1/s/salatino/cori/s4cmb/s4cmb/__init__.pyc

**Comment by JulienPeloton** [comment]
OK all right then! Have fun with the code :-)

**Comment by MariaJK** [comment]
thanks for your help Julien!
Maria
