### ISSUE TITLE
Assertion Error in tod.py

### ISSUE THREAD

**Issue by joydidier** [JulienPeloton/s4cmb#23]
I was trying to get the so_MC_app.py running and noticed I got an error that I didn't get with simple_app.py.
I traced it down to this difference in code between the two example apps:

== in simple_app.py ==
```
           d = []
           for det in tqdm(range(inst.focal_plane.nbolometer)):
                d.append(tod.map2tod(det))
           ## Project TOD to maps
           tod.tod2map(np.array(d), sky_out_tot)
```

== in so_MC_app.py ==

```
         for pair in tod.pair_list:
                d = np.array([tod.map2tod(det) for det in pair])
                ## Project TOD to maps
                tod.tod2map(d, sky_out_tot)
```

When I use the "so_MC_app" way in the simple app, I get the same error.
The error is:

Traceback (most recent call last):
  File "examples/test/simple_app.py", line 179, in <module>
    tod.tod2map(d, sky_out_tot)
  File "/data/home/joy/simons_observatory/code/s4cmb/s4cmb/tod.py", line 635, in tod2map
    assert npixfp == self.point_matrix.shape[0]
AssertionError

Do you understand what's going on? Does the use of one code vs the other has to match the "perpair" parameter?
Thanks!!

**Comment by JulienPeloton** [comment]
The way you loop over focal plane pixel to do the mapmaking depends indeed on the value of `mapping_perpair` parameter. In simple_app.py, one first load all the pixel (and set `mapping_perpair=False` in the tod initialisation) and then perform the mapmaking with all the pixels at once. In so_MC_app.py, the mapmaking is done pair-by-pair (and `mapping_perpair=True`). 

You closed the issue because you found the solution, or by mistake?

**Comment by joydidier** [comment]
Hi Julien,
I closed the issue because it seemed it was linked to perpair value and so I understood it . Though now that I think about it, it might be worth adding an print message in the function that gives the assertion error— when using the compiled code (from pip install) it’s hard to trace back the error, and a print message saying « check that mapping_perpair is set to X » would be very helpful.
Joy

**Comment by JulienPeloton** [comment]
You are right, I will make it clearer! Thanks!

**Comment by joydidier** [comment]
Thanks!!

**Comment by JulienPeloton** [comment]
I have changed the [code](https://github.com/JulienPeloton/s4cmb/commit/b3f724ce3588b9bbfa4e033d8f487de5aa20eb52) accordingly. Should be clearer now!
