### ISSUE TITLE
Replace inifiles with python files for launching Apps?

### ISSUE THREAD

**Issue by JulienPeloton** [JulienPeloton/s4cmb#3]
The fact that we are currently using inifiles to define parameters to be used in App is only historical.
There is no real advantage using inifiles over python if the main script is in python.
First, it makes things more complex (needed to introduce an extra step using NormaliseParser to decode it), and second I think that if one can do something in python without suffering much, one must do.

**Comment by joydidier** [comment]
Just quick comment to say I agree -- on EBEX we used python files for settings and it worked very well and is less cumbersome than ini files. Also, two other related thoughts on settings: a) if each app is in its own directory, then all parameter files can be named "default_settings.py" and the app can by default look for this file in its directory b) one can setup a "default_settings.py" which is saved in the repo with default values for an app to run, and then there can be a "custom_settings.py" which overwrites default_settings.py (for the parameters specified in custom) that people can edit freely. custom_settings.py is not saved to the repo. This enables multiple people to play with the same app without overwriting each others settings, while keeping a model settings for any app

**Comment by JulienPeloton** [comment]
Thanks for pushing for that.
I opened a branch, and start to move all ini files into python ones. I will let you know the final merge.

Good point using a separate default and custom settings file, although this is already the case with simple_parameters.{ini, py}.

**Comment by JulienPeloton** [comment]
Done - now ini files are in python and I created folders to avoid the mess!

**Comment by JulienPeloton** [comment]
Note that the way Apps work has been updated, to import python module directly.
