### ISSUE TITLE
no origin/dichroic branch

### ISSUE THREAD

**Issue by MariaJK** [JulienPeloton/s4cmb#30]
Hi Julien,

I would like to try the dichroich example:
https://github.com/JulienPeloton/s4cmb-resources/blob/master/Part1/s4cmb_dichroic_06.ipynb

for which I need to checkout the origin/dichroic branch'.
I have never used before git, so I am a very new user. I tried looking online/forums but I still have the issue.

Basically, I do not see the 'origin/dichroich' branch in my local copy.
I tried several commands (fetch, pull origin master etc etc)....
I did:

> git pull origin master

> From https://github.com/MariaJK/s4cmb
> * branch            master     -> FETCH_HEAD
> Already up-to-date.

> git branch -r

> origin/HEAD -> origin/master
> origin/beam_ellipticity
> origin/master

Moreover, looking at the github repo pag, https://github.com/JulienPeloton/s4cmb,
I only see 'master' and 'correlated_noise'. Joy found the same.

Could you help me?
Thanks,
Maria

**Comment by JulienPeloton** [comment]
Hi Maria!

The branch dichroic doesn't exist anymore - I merged it and deleted it (see this [PR](https://github.com/JulienPeloton/s4cmb/pull/28))
So you can run the notebook from the master branch as usual.
Sorry, I should have updated the doc :-(

Julien

**Comment by MariaJK** [comment]
Hi Julien,

ok. I saw it in 'https://github.com/JulienPeloton/s4cmb/blob/master/s4cmb/instrument.py'
but when I run Jupyter at NERSC, I got:
> AttributeError: Hardware instance has no attribute 'make_dichroic'

so, it is not updated/synchronized.
Sorry, what should I do to synch my copy of the repo at cori/nersc with your one?

Merci,
Maria

**Comment by JulienPeloton** [comment]
If you want to update your fork with my repo (i.e. take my modifications to the fork on your account), you need to sync it with my repo:

**configuring a remote for the fork (To do once)**
go to your master branch
`git checkout master`
List the current configured remote repository for your fork:
`git remote -v`
Add the original
`git remote add upstream https://github.com/JulienPeloton/s4cmb.git`
Verify the new upstream repository you've specified for your fork.
`git remote -v`

**Syncing a fork with the original (each time you want to incorporate new modifs from my repo)**
`git fetch upstream`
`git merge upstream/master`

You should have all the modifs that I pushed.
Attention, if you made modifications on your repo, you might have conflict to solve during the merge.

**Comment by MariaJK** [comment]
Thanks a lot Julien!
It worked!
Sprry for disturbing you!
Maria

**Comment by JulienPeloton** [comment]
Great!
Julien
