### ISSUE TITLE
Pixels outside obspix with deep_patch

### ISSUE THREAD

**Issue by Helbouha** [JulienPeloton/s4cmb#33]
Hi Julien ! 

Is it normal to have pixels falling outside the list of observed pixels (obspix) with the "deep_patch" scanning strategy, when we set width = 130 (default value) ?

Below is the inverse condition number of each pixel (1 CES, nside = 128), I realized with mollview that some pixels fall clearly out of the main sky patch defined by the scan.

![rcond_128_issue](https://user-images.githubusercontent.com/38554781/51698402-618e7a80-200a-11e9-991a-aaa40bb31ac4.png)

**Comment by JulienPeloton** [comment]
Hi Hamza!

Thanks for reporting this. Yes, this is (unfortunately) expected... 

This spurious pixel is basically observed only once (hence the super low condition number as you see). I suspect a bug in the initialisation of the scanning strategy: it starts at `(lon, lat) = (0, 0)` for the first time sample, and then goes to the user-defined region on the sky.

I never found time to correct it, and I was lazily flagging it afterwards... Let me have a quick look.

**Comment by JulienPeloton** [comment]
I've produced a fix in #35. Can you check it works in your case as well?

**Comment by Helbouha** [comment]
I've just checked the fix, it works !

![rcond_128_fixed](https://user-images.githubusercontent.com/38554781/51744304-b4664180-209f-11e9-94d9-dbcfc7f9a52d.png)

Thanks a lot !

**Comment by JulienPeloton** [comment]
Great! I will merge the PR then.
