### ISSUE TITLE
test suite -- are the flat and curved map in the tod.py tests really equal to within 1%? I see 2.5% 

### ISSUE THREAD

**Issue by joydidier** [JulienPeloton/s4cmb#4]
The two maps are equal to within 2.5% on my machine hence the test suite fails when running ./coverage_and_test.sh

**Comment by JulienPeloton** [comment]
Good catch. I recently changed the way flat sky is handled, and for convenience (or laziness) curve vs flat cannot be compared anymore... Let me remove this test asap.

**Comment by JulienPeloton** [comment]
Done. I might need to think of a new test though...
