### ISSUE TITLE
Main figure not visible with GitHub Dark mode

### ISSUE THREAD

**Issue by aboucaud** [JulienPeloton/s4cmb#61]
The figure is pretty but the display is very poor with the dark mode activated.
A white background may be necessary (for once! :)
![image](https://user-images.githubusercontent.com/3065310/116389673-80010300-a81d-11eb-875f-fabb3e745427.png)

**Comment by JulienPeloton** [comment]
ah ah, epic fail :D

Thanks @aboucaud for spotting it, I will update the figure background.

**Comment by JulienPeloton** [comment]
The figure has been updated thanks to @markm42 (#62) -- thanks all!
